### ISSUE TITLE
Create a shared document for our project

### ISSUE THREAD

**Issue by iloonio** [LevelWard/projekt_labb142g#1]

**Comment by Valhalla1010** [comment]
hej

**Comment by Valhalla1010** [comment]
Webbsidan

**Comment by iloonio** [comment]
varför öppnade du denna issue? jag stängde den eftersom vi har ett delad dokument

**Comment by Valhalla1010** [comment]
Förlåt mig 🙏, jag gjorde fel.😞

Med vänlig hälsning
David Marzban
________________________________
