### ISSUE TITLE
KitchenOverview boxes display order_id, not table_number

### ISSUE THREAD

**Issue by iloonio** [LevelWard/projekt_labb142g#59]
![image](https://github.com/LevelWard/projekt_labb142g/assets/98955978/ba16fdca-77dd-4874-b9ee-111de3ccfc5b)

se figuren ovanför. Denna order skapades med table_number = 3, men i bilden står det "table number: 42" 
När dessa ordrar markeras klara dyker de upp i OrderOverview som bordsnummer (vilket är korrekt) 

Möjliga sätt att korrigera det här på: 

- [ ]  Behandla beställningar som enkla ordrar, ta bort bord från köksvyn helt
- [ ]  Implementera någon slags metod som kommer att på något sätt hämta bord associerat till order (detta innebär ändrade db anrop i köksvyn)

**Comment by LevelWard** [comment]
Ändrat så att det är tänkt att orderID visas.
